// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TheDojoLeague.Models;

namespace TheDojoLeague.Migrations
{
    [DbContext(typeof(DojoLeagueContext))]
    [Migration("20180516203159_RemovedReverse")]
    partial class RemovedReverse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("TheDojoLeague.Models.Dojos", b =>
                {
                    b.Property<int>("DojoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalDojoInformation")
                        .IsRequired();

                    b.Property<string>("DojoLocation")
                        .IsRequired();

                    b.Property<string>("DojoName")
                        .IsRequired();

                    b.HasKey("DojoId");

                    b.ToTable("Dojos");
                });

            modelBuilder.Entity("TheDojoLeague.Models.Ninjas", b =>
                {
                    b.Property<int>("NinjaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DojoId");

                    b.Property<string>("NinjaName")
                        .IsRequired();

                    b.Property<int>("NinjaingLevel");

                    b.Property<string>("OptionalDescription")
                        .IsRequired();

                    b.HasKey("NinjaId");

                    b.HasIndex("DojoId");

                    b.ToTable("Ninjas");
                });

            modelBuilder.Entity("TheDojoLeague.Models.Ninjas", b =>
                {
                    b.HasOne("TheDojoLeague.Models.Dojos", "Dojos")
                        .WithMany("Ninjas")
                        .HasForeignKey("DojoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
